#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 05 16:57:51 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim AlohaHE_wrapper_behav -key {Behavioral:sim_1:Functional:AlohaHE_wrapper} -tclbatch AlohaHE_wrapper.tcl -protoinst "protoinst_files/bd_7499.protoinst" -protoinst "protoinst_files/AlohaHE.protoinst" -log simulate.log"
xsim AlohaHE_wrapper_behav -key {Behavioral:sim_1:Functional:AlohaHE_wrapper} -tclbatch AlohaHE_wrapper.tcl -protoinst "protoinst_files/bd_7499.protoinst" -protoinst "protoinst_files/AlohaHE.protoinst" -log simulate.log

