# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Genesys-2-Master.xdc

# Block Designs: bd/CKKS/CKKS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS || ORIG_REF_NAME==CKKS} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_bram_ctrl_0_0/CKKS_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_bram_ctrl_0_0 || ORIG_REF_NAME==CKKS_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_bram_ctrl_0_bram_0/CKKS_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==CKKS_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_bram_ctrl_1_0/CKKS_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_bram_ctrl_1_0 || ORIG_REF_NAME==CKKS_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_cdma_0_0/CKKS_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_cdma_0_0 || ORIG_REF_NAME==CKKS_axi_cdma_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_xbar_0/CKKS_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_xbar_0 || ORIG_REF_NAME==CKKS_xbar_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_interconnect_0_0/CKKS_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_interconnect_0_0 || ORIG_REF_NAME==CKKS_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_xbar_1/CKKS_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_xbar_1 || ORIG_REF_NAME==CKKS_xbar_1} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_axi_interconnect_1_0/CKKS_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_axi_interconnect_1_0 || ORIG_REF_NAME==CKKS_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_clk_wiz_0_0/CKKS_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_clk_wiz_0_0 || ORIG_REF_NAME==CKKS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_neorv32_vivado_ip_0_0/CKKS_neorv32_vivado_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_neorv32_vivado_ip_0_0 || ORIG_REF_NAME==CKKS_neorv32_vivado_ip_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_proc_sys_reset_0_0/CKKS_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_proc_sys_reset_0_0 || ORIG_REF_NAME==CKKS_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_xlconcat_0_0/CKKS_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_xlconcat_0_0 || ORIG_REF_NAME==CKKS_xlconcat_0_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_auto_pc_0/CKKS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_auto_pc_0 || ORIG_REF_NAME==CKKS_auto_pc_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_auto_us_0/CKKS_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_auto_us_0 || ORIG_REF_NAME==CKKS_auto_us_0} -quiet] -quiet

# IP: bd/CKKS/ip/CKKS_auto_ds_0/CKKS_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CKKS_auto_ds_0 || ORIG_REF_NAME==CKKS_auto_ds_0} -quiet] -quiet

# XDC: bd/CKKS/CKKS_ooc.xdc
