webtalk_init -webtalk_dir /home/sam/Documents/thesis-defense/thesis_Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.sim/sim_1/behav/xsim/xsim.dir/test_ComputeCoreWrapper_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 22 18:05:59 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211253938_177879426_210784857_048" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "287349d9-8da6-4662-a45e-5cfbce359f24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "45b487749c1f41099588870e48665600" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2720.725 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "144472_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1976410495 -regid "211253938_177879426_210784857_048" -xml /home/sam/Documents/thesis-defense/thesis_Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.sim/sim_1/behav/xsim/xsim.dir/test_ComputeCoreWrapper_test_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sam/Documents/thesis-defense/thesis_Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.sim/sim_1/behav/xsim/xsim.dir/test_ComputeCoreWrapper_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sam/Documents/thesis-defense/thesis_Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.sim/sim_1/behav/xsim/xsim.dir/test_ComputeCoreWrapper_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
