#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sun Oct 20 15:47:10 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --relax -prj test_CKKS_vlog.prj"
xvlog --relax -prj test_CKKS_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --relax -prj test_CKKS_vhdl.prj"
xvhdl --relax -prj test_CKKS_vhdl.prj 2>&1 | tee -a compile.log

