#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 21 22:41:40 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6e273518fd134faeac3b4d919c23950d --debug typical --relax --mt 8 -L axi_bram_ctrl_v4_1_1 -L xil_defaultlib -L blk_mem_gen_v8_4_3 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L fifo_generator_v13_2_4 -L lib_fifo_v1_0_13 -L lib_cdc_v1_0_2 -L axi_datamover_v5_1_21 -L axi_sg_v4_1_12 -L axi_cdma_v4_1_19 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L dist_mem_gen_v8_0_13 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_dsp48_macro_v3_0_17 -L neorv32 -L proc_sys_reset_v5_0_13 -L xlconcat_v2_1_3 -L axi_protocol_converter_v2_1_19 -L axi_clock_converter_v2_1_18 -L axi_dwidth_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot test_CKKS_behav xil_defaultlib.test_CKKS xil_defaultlib.glbl -log elaborate.log"
xelab -wto 6e273518fd134faeac3b4d919c23950d --debug typical --relax --mt 8 -L axi_bram_ctrl_v4_1_1 -L xil_defaultlib -L blk_mem_gen_v8_4_3 -L lib_pkg_v1_0_2 -L lib_srl_fifo_v1_0_2 -L fifo_generator_v13_2_4 -L lib_fifo_v1_0_13 -L lib_cdc_v1_0_2 -L axi_datamover_v5_1_21 -L axi_sg_v4_1_12 -L axi_cdma_v4_1_19 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_19 -L axi_data_fifo_v2_1_18 -L axi_crossbar_v2_1_20 -L dist_mem_gen_v8_0_13 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_dsp48_macro_v3_0_17 -L neorv32 -L proc_sys_reset_v5_0_13 -L xlconcat_v2_1_3 -L axi_protocol_converter_v2_1_19 -L axi_clock_converter_v2_1_18 -L axi_dwidth_converter_v2_1_19 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot test_CKKS_behav xil_defaultlib.test_CKKS xil_defaultlib.glbl -log elaborate.log

