# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sam/Documents/thesis-defense/defense_design/CFS_design/CFS_design.srcs/sources_1/bd/CKKS/ip/CKKS_xbar_1/CKKS_xbar_1.xci
# IP: The module: 'CKKS_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sam/Documents/thesis-defense/defense_design/CFS_design/CFS_design.srcs/sources_1/bd/CKKS/ip/CKKS_xbar_1/CKKS_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CKKS_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sam/Documents/thesis-defense/defense_design/CFS_design/CFS_design.srcs/sources_1/bd/CKKS/ip/CKKS_xbar_1/CKKS_xbar_1.xci
# IP: The module: 'CKKS_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sam/Documents/thesis-defense/defense_design/CFS_design/CFS_design.srcs/sources_1/bd/CKKS/ip/CKKS_xbar_1/CKKS_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CKKS_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
